blank_issues_enabled: false
contact_links:
  - name: StumpStudio Discord
    url: https://discord.gg/qAdSNQW
    about: If you have any other problems or questions, do not hesitate to join our Discord server.
