locale: en
check-for-updates: true
x-mode: false
crawl:
  static: false
  stand-up-when-damaged: true
  enabled: true
lay:
  view-distance: 20 #Measures in blocks
  stand-up-when-damaged: true
  head-rotation: true
  swing-animation: true
  sync-equipment: true
  prevent-use-when-invisible: true
  sync-overlays: true
sit:
  stand-up-when-damaged: true
wave:
  enabled: true
  stand-up-when-damaged: true
  disable-when-shift: true
point:
  enabled: true
  stand-up-when-damaged: true
  disable-when-shift: true
handshake:
  enabled: true
  stand-up-when-damaged: true
  disable-when-shift: true
pray:
  enabled: true
  step: 3.0
